name: integration
on: [push, pull_request, workflow_dispatch]
jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v1

      # run any `bun` or `bunx` command
      - run: bun install
      - run: bun run tsc --noEmit
      - run: bun test
